DEPTH                 = ..

INTERFACE_HOME        = ../axi_if

AXI_DEFINATION_HOME   = $(DEPTH)/axi_top
AXI_DEFINATION_FILE   = $(AXI_DEFINATION_HOME)/axi_defination_pkg.sv

BUS_MASTER_AGNT_HOME  = $(DEPTH)/axi_master_agent_pkg
BUS_MASTER_AGNT_FILES = $(BUS_MASTER_AGNT_HOME)/axi_master_agent_pkg.sv
BUS_SLAVE_AGNT_HOME   = $(DEPTH)/axi_slave_agent_pkg
BUS_SLAVE_AGNT_FILES  = $(BUS_SLAVE_AGNT_HOME)/axi_slave_agent_pkg.sv

SEQ_HOME              = $(DEPTH)/axi_sequence_pkg
SEQ_PKG               = $(SEQ_HOME)/axi_sequence_pkg.sv

BUS_ENV_HOME          = $(DEPTH)/axi_environment_pkg
BUS_ENV_FILES         = $(BUS_ENV_HOME)/axi_environment_pkg.sv

BUS_TEST_HOME         = $(DEPTH)/axi_test_pkg
BUS_TEST_FILES        = $(BUS_TEST_HOME)/axi_test_pkg.sv

BUS_TOP_HOME          = $(DEPTH)/axi_top
BUS_TOP_FILES         = $(BUS_TOP_HOME)/axi_top.sv

COVOPT      = -coveropt 3 +cover +acc
COV0 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov0; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV1 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov1; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV2 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov2; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV3 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov3; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV4  = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov4; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV5  = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov5; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV6  = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov6; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV7  = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov7; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV8  = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov8; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV9  = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov9; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV10 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov10; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV11 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov11; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV12 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov12; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV13 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov13; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV14 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov14; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV15 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov15; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV16 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov16; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV17 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov17; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV18 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov18; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV19 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov19; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV20 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov20; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV21 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov21; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV22 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov22; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV23 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov23; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV24 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov24; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV25 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov25; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV26 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov26; set SolveArrayResizeMax 0; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva axi_top
COV27 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov27; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV28 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov28; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV29 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov29; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top
COV30 = -c -do "coverage save -onexit -assert -directive -cvg -codeAll axi_cov30; set SolveArrayResizeMax 0; run -all;exit" -coverage -novopt -sva -sv_seed 895623 axi_top

lib:
	vlib work

comp:
	 vlog\
		  $(COVOPT) \
		  +incdir+$(INTERFACE_HOME) \
		  +incdir+$(AXI_DEFINATION_HOME) \
		  +incdir+$(BUS_MASTER_AGNT_HOME) \
		  +incdir+$(BUS_SLAVE_AGNT_HOME) \
		  +incdir+$(BUS_ENV_HOME) \
		  +incdir+$(SEQ_HOME) \
		  +incdir+$(BUS_TEST_HOME) \
		  +incdir+$(BUS_TOP_HOME) \
		  $(AXI_DEFINATION_FILE) \
		  $(BUS_MASTER_AGNT_FILES) \
		  $(BUS_SLAVE_AGNT_FILES) \
		  $(BUS_ENV_FILES) \
		  $(SEQ_PKG) \
		  $(BUS_TEST_FILES)\
		  $(BUS_TOP_FILES)
#------------------------------------------		  
#------------------------------------------		  

TC0:
	vsim $(COV0) +UVM_TESTNAME=axi_rand_write_test +UVM_VERBOSITY=MEDIUM
	vcover report -html axi_cov0
gui0:
	vsim -novopt axi_top +UVM_TESTNAME=axi_rand_write_test +UVM_VERBOSITY=UVM_MEDIUM

TC1:
	vsim $(COV1) +UVM_TESTNAME=axi_rand_read_test
	vcover report -html axi_cov1
gui1:
	vsim -novopt axi_top +UVM_TESTNAME=axi_rand_read_test

TC2:
	vsim $(COV2) +UVM_TESTNAME=axi_fixed_write_test 
	vcover report -html axi_cov2
gui2:
	vsim -novopt axi_top +UVM_TESTNAME=axi_fixed_write_test 

TC3:
	vsim $(COV3) +UVM_TESTNAME=axi_incr_write_test 
	vcover report -html axi_cov3
gui3:
	vsim -novopt axi_top +UVM_TESTNAME=axi_incr_write_test 
TC4:
	vsim $(COV4) +UVM_TESTNAME=axi_wrap_write_test 
	vcover report -html axi_cov4
gui4:
	vsim -novopt axi_top +UVM_TESTNAME=axi_wrap_write_test 
TC5:
	vsim $(COV5) +UVM_TESTNAME=axi_fixed_read_test 
	vcover report -html axi_cov5
gui5:
	vsim -novopt axi_top +UVM_TESTNAME=axi_fixed_read_test 
TC6:
	vsim $(COV6) +UVM_TESTNAME=axi_incr_read_test 
	vcover report -html axi_cov6
gui6:
	vsim -novopt axi_top +UVM_TESTNAME=axi_incr_read_test 
TC7:
	vsim $(COV7) +UVM_TESTNAME=axi_wrap_read_test 
	vcover report -html axi_cov7
gui7:
	vsim -novopt axi_top +UVM_TESTNAME=axi_wrap_read_test 
TC8:
	vsim $(COV8) +UVM_TESTNAME=axi_fixed_write_to_read_test 
	vcover report -html axi_cov8
gui8:
	vsim -novopt axi_top +UVM_TESTNAME=axi_fixed_write_to_read_test 
TC9:
	vsim $(COV9) +UVM_TESTNAME=axi_incr_write_to_read_test 
	vcover report -html axi_cov9
gui9:
	vsim -novopt axi_top +UVM_TESTNAME=axi_incr_write_to_read_test 
TC10:
	vsim $(COV10) +UVM_TESTNAME=axi_wrap_write_to_read_test 
	vcover report -html axi_cov10
gui10:
	vsim -novopt axi_top +UVM_TESTNAME=axi_wrap_write_to_read_test 
#---------------------------------------
#---------------------------------------
TC11:
	vsim $(COV11) +UVM_TESTNAME=axi_aligned_fixed_write_test
	vcover report -html axi_cov11
gui11:
	vsim -novopt axi_top +UVM_TESTNAME=axi_aligned_fixed_write_test
TC12:
	vsim $(COV12) +UVM_TESTNAME=axi_aligned_incr_write_test
	vcover report -html axi_cov12
gui12:
	vsim -novopt axi_top +UVM_TESTNAME=axi_aligned_incr_write_test
TC13:
	vsim $(COV13) +UVM_TESTNAME=axi_aligned_wrap_write_test
	vcover report -html axi_cov13
gui13:
	vsim -novopt axi_top +UVM_TESTNAME=axi_aligned_wrap_write_test
TC14:
	vsim $(COV14) +UVM_TESTNAME=axi_aligned_fixed_read_test
	vcover report -html axi_cov14
gui14:
	vsim -novopt axi_top +UVM_TESTNAME=axi_aligned_fixed_read_test
TC15:
	vsim $(COV15) +UVM_TESTNAME=axi_aligned_incr_read_test
	vcover report -html axi_cov15
gui15:
	vsim -novopt axi_top +UVM_TESTNAME=axi_aligned_incr_read_test
TC16:
	vsim $(COV16) +UVM_TESTNAME=axi_aligned_wrap_read_test
	vcover report -html axi_cov16
gui16:
	vsim -novopt axi_top +UVM_TESTNAME=axi_aligned_wrap_read_test
TC17:
	vsim $(COV17) +UVM_TESTNAME=axi_unaligned_fixed_write_test
	vcover report -html axi_cov17
gui17:
	vsim -novopt axi_top +UVM_TESTNAME=axi_unaligned_fixed_write_test
TC18:
	vsim $(COV18) +UVM_TESTNAME=axi_unaligned_incr_write_test
	vcover report -html axi_cov18
gui18:
	vsim -novopt axi_top +UVM_TESTNAME=axi_unaligned_incr_write_test
TC19:
	vsim $(COV19) +UVM_TESTNAME=axi_unaligned_wrap_write_test
	vcover report -html axi_cov19
gui19:
	vsim -novopt axi_top +UVM_TESTNAME=axi_unaligned_wrap_write_test
TC20:
	vsim $(COV20) +UVM_TESTNAME=axi_unaligned_fixed_read_test
	vcover report -html axi_cov20
gui20:
	vsim -novopt axi_top +UVM_TESTNAME=axi_unaligned_fixed_read_test
TC21:
	vsim $(COV21) +UVM_TESTNAME=axi_unaligned_incr_read_test
	vcover report -html axi_cov21
gui21:
	vsim -novopt axi_top +UVM_TESTNAME=axi_unaligned_incr_read_test
TC22:
	vsim $(COV22) +UVM_TESTNAME=axi_unaligned_wrap_read_test
	vcover report -html axi_cov22
gui22:
	vsim -novopt axi_top +UVM_TESTNAME=axi_unaligned_wrap_read_test
TC23:
	vsim $(COV23) +UVM_TESTNAME=axi_fixed_narrow_write_to_read_test
	vcover report -html axi_cov23
gui23:
	vsim -novopt axi_top +UVM_TESTNAME=axi_fixed_narrow_write_to_read_test
TC24:
	vsim $(COV24) +UVM_TESTNAME=axi_incr_narrow_write_to_read_test
	vcover report -html axi_cov24
gui24:
	vsim -novopt axi_top +UVM_TESTNAME=axi_incr_narrow_write_to_read_test
TC25:
	vsim $(COV25) +UVM_TESTNAME=axi_wrap_narrow_write_to_read_test
	vcover report -html axi_cov25
gui25:
	vsim -novopt axi_top +UVM_TESTNAME=axi_wrap_narrow_write_to_read_test
#-------------
#-------------
TC26:
	vsim $(COV26) +UVM_TESTNAME=axi_rand_outstand_write_test
	vcover report -html axi_cov26
gui26:
	vsim -novopt axi_top +UVM_TESTNAME=axi_rand_outstand_write_test -do "set SolveArrayResizeMax 0; run -all"
TC27:
	vsim $(COV27) +UVM_TESTNAME=axi_rand_outstand_read_test
	vcover report -html axi_cov27
gui27:
	vsim -novopt axi_top +UVM_TESTNAME=axi_rand_outstand_read_test
#-------------
#-------------
TC28:
	vsim $(COV28) +UVM_TESTNAME=axi_fixed_simultaneous_write_read_test
	vcover report -html axi_cov28
gui28:
	vsim -novopt axi_top +UVM_TESTNAME=axi_fixed_simultaneous_write_read_test
TC29:
	vsim $(COV29) +UVM_TESTNAME=axi_incr_simultaneous_write_read_test
	vcover report -html axi_cov29
gui29:
	vsim -novopt axi_top +UVM_TESTNAME=axi_incr_simultaneous_write_read_test
TC30:
	vsim $(COV30) +UVM_TESTNAME=axi_wrap_simultaneous_write_read_test
	vcover report -html axi_cov30
gui30:
	vsim -novopt axi_top +UVM_TESTNAME=axi_wrap_simultaneous_write_read_test
